services:
  app:
    build: .
    platform: linux/arm64/v8
    shm_size: '16gb'
    volumes:
      - ./:/kaggle
        ./input /kaggle/input
        ./scripts /kaggle/scripts
    working_dir: /kaggle
    ports:
      - "8888:8888"
    tty: true